- name: Disable ssh root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin No"

- name: Disable password ssh login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^ChallengeResponseAuthentication" line="ChallengeResponseAuthentication No"

- name: Disable root password
  command: pw user mod root -w no
