---
- include: password.yml
- include: ntp.yml
- include: autoupdate.yml

- include: ssmtp.yml
  when: bootstrap_ssmtp_server is defined

- include: runit.yml
- include: fstab.yml
- include: packages.yml

- include: locale.yml
- include: syslog.yml
