---
- name: Disable ssh root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin No"

- name: Disable password ssh login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^ChallengeResponseAuthentication" line="ChallengeResponseAuthentication No"

- name: Disable root password
  command: pw user mod root -w no

- name: Install ntp
  pkgng: name=ntp

- name: Enable ntp
  service: name=ntpd state=started enabled=yes

- name: Set auto update to daily
  lineinfile: 
    dest: /etc/crontab 
    regexp: freebsd-update cron
    line: "@daily                                  root    freebsd-update cron"


- include: ssmtp.yml
  when: bootstrap_ssmtp_server is defined

- name: Install runit
  pkgng: name=runit

- name: Enable runit
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^runsvdir_enable
    line: runsvdir_enable="YES"

- name: Start runit
  service: name=runsvdir state=restarted

- name: Add proc to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: ^proc
    line: proc /proc procfs rw 0 0


- name: Add fdesc to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: ^fdesc
    line: fdesc /dev/fd fdescfs rw 0 0

- name: Mount all
  command: mount -a


- name: Install base packages
  pkgng: name={{ item }}
  with_items:
  - rsync

- include: syslog.yml
